################# Camera Configs ########################
USE_CAMERA_STUB := true
BOARD_USE_SPRD_COLORFORMAT := true

TARGET_BOARD_BACK_CAMERA_ROTATION := false
TARGET_BOARD_FRONT_CAMERA_ROTATION := false

CAMERA_SENSOR_TYPE_BACK := "s5k4h5yc_mipi"
CAMERA_SENSOR_TYPE_FRONT := "s5k5e3yx_mipi"

CAMERA_SUPPORT_SIZE := 8M
FRONT_CAMERA_SUPPORT_SIZE := 5M
TARGET_BOARD_CAMERA_SMJ320 := true
TARGET_BOARD_NO_FRONT_SENSOR := false
TARGET_BOARD_CAMERA_FLASH_CTRL := false

TARGET_BOARD_CAMERA_READOTP_METHOD := 1

TARGET_BOARD_CAMERA_FACE_DETECT := true
TARGET_BOARD_CAMERA_FD_LIB := omron

TARGET_BOARD_CAMERA_HDR_CAPTURE := true

TARGET_BOARD_BACK_CAMERA_INTERFACE := mipi
TARGET_BOARD_FRONT_CAMERA_INTERFACE := mipi
TARGET_BOARD_CAMERA_CAPTURE_MODE := true

TARGET_BOARD_CAMERA_FORCE_ZSL_MODE := true
TARGET_BOARD_CAMERA_SPRD_PRIVATE_ZSL := false

TARGET_BOARD_CAMERA_ROTATION_CAPTURE := false
TARGET_BOARD_CAMERA_NO_AUTOFOCUS_DEV := false

TARGET_BOARD_CAMERA_CAPTURE_DENOISE := false
TARGET_BOARD_CAMERA_Y_DENOISE := true
TARGET_BOARD_CAMERA_CAF := true
TARGET_BOARD_CAMERA_NO_FLASH_DEV := false

TARGET_BOARD_CAMERA_ADAPTER_IMAGE := 0

TARGET_BOARD_CAMERA_PRE_ALLOC_CAPTURE_MEM := true
TARGET_BOARD_CAMERA_ISP_SOFTWARE_VERSION := 2

TARGET_USES_MEDIA_EXTENSIONS := true
TARGET_BOARD_CAMERA_HAL_VERSION := 1.0

TARGET_BOARD_CAMERA_ANTI_FLICKER := true
TARGET_BOARD_MULTI_CAP_MEM := true
TARGET_BOARD_LOW_CAPTURE_MEM := true

# Select the VCM chip driver BU64241GWZ
TARGET_VCM_BU64241GWZ := true

# Select MIPI d-phy mode (none, phya, phyb, phyab)
TARGET_BOARD_FRONT_CAMERA_MIPI := phyb
TARGET_BOARD_BACK_CAMERA_MIPI := phya

# Select CCIE PCLK source (source0, source1)
TARGET_BOARD_FRONT_CAMERA_CCIR_PCLK := source0
TARGET_BOARD_BACK_CAMERA_CCIR_PCLK := source0

TARGET_BOARD_USE_THRID_LIB := true
TARGET_BOARD_USE_THIRD_AWB_LIB_A := true
TARGET_BOARD_USE_ALC_AE_AWB := false
TARGET_BOARD_USE_THIRD_AF_LIB_A := true
